
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "docker.io/go-docker"
  version = "1.0.0"

[[constraint]]
  name = "github.com/BurntSushi/toml"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.4.22"

[[constraint]]
  name = "github.com/docker/distribution"

[[constraint]]
  name = "github.com/docker/libnetwork"

[[constraint]]
  name = "github.com/hashicorp/go-version"

[[constraint]]
  name = "github.com/koron/go-dproxy"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/stvp/rollbar"
  version = "0.5.0"

[[constraint]]
  name = "github.com/tcnksm/go-latest"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/jessevdk/go-assets"
